// This file will be auto-generated by running:
// npx supabase gen types typescript --project-id your-project-id > types/database.ts
// For now, here's the manual type definition based on our schema:

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          name: string | null
          avatar_url: string | null
          subscription_status: 'free' | 'premium' | 'canceled'
          subscription_id: string | null
          subscription_end_date: string | null
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          name?: string | null
          avatar_url?: string | null
          subscription_status?: 'free' | 'premium' | 'canceled'
          subscription_id?: string | null
          subscription_end_date?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          avatar_url?: string | null
          subscription_status?: 'free' | 'premium' | 'canceled'
          subscription_id?: string | null
          subscription_end_date?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
      }
      entries: {
        Row: {
          id: string
          user_id: string
          event: string | null
          thought: string | null
          feelings: string[]
          other_feeling: string | null
          category: string | null
          intensity: number
          health: Json
          voice_note_url: string | null
          voice_note_duration: number | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          event?: string | null
          thought?: string | null
          feelings?: string[]
          other_feeling?: string | null
          category?: string | null
          intensity?: number
          health?: Json
          voice_note_url?: string | null
          voice_note_duration?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          event?: string | null
          thought?: string | null
          feelings?: string[]
          other_feeling?: string | null
          category?: string | null
          intensity?: number
          health?: Json
          voice_note_url?: string | null
          voice_note_duration?: number | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      subscription_status: 'free' | 'premium' | 'canceled'
    }
  }
}

// Helper types for the app
export type Profile = Database['public']['Tables']['profiles']['Row']
export type Entry = Database['public']['Tables']['entries']['Row']
export type NewEntry = Database['public']['Tables']['entries']['Insert']

export interface HealthData {
  cycleDay: string
  cyclePhase: string
  sleep: string
  factors: string[]
  otherFactor: string
}

export interface UserSettings {
  trackCycle: boolean
  trackSleep: boolean
  trackHealth: boolean
  periodStartDate: string
  averageCycleLength: number
  notificationsEnabled: boolean
  notificationTime: string
}
