// This file will be auto-generated by running:
// npx supabase gen types typescript --project-id your-project-id > lib/supabase/database.types.ts
// For now, we define the types manually:

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          name: string | null
          avatar_url: string | null
          subscription_status: 'free' | 'premium' | 'cancelled'
          subscription_id: string | null
          subscription_end_date: string | null
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          name?: string | null
          avatar_url?: string | null
          subscription_status?: 'free' | 'premium' | 'cancelled'
          subscription_id?: string | null
          subscription_end_date?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          avatar_url?: string | null
          subscription_status?: 'free' | 'premium' | 'cancelled'
          subscription_id?: string | null
          subscription_end_date?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
      }
      entries: {
        Row: {
          id: string
          user_id: string
          event: string | null
          category: string | null
          thought: string | null
          feelings: string[]
          other_feeling: string | null
          intensity: number
          health: Json
          voice_note_url: string | null
          voice_note_duration: number | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          event?: string | null
          category?: string | null
          thought?: string | null
          feelings?: string[]
          other_feeling?: string | null
          intensity?: number
          health?: Json
          voice_note_url?: string | null
          voice_note_duration?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          event?: string | null
          category?: string | null
          thought?: string | null
          feelings?: string[]
          other_feeling?: string | null
          intensity?: number
          health?: Json
          voice_note_url?: string | null
          voice_note_duration?: number | null
          created_at?: string
        }
      }
    }
  }
}

export type Profile = Database['public']['Tables']['profiles']['Row']
export type Entry = Database['public']['Tables']['entries']['Row']
